### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by marknp** [chris220688/garmin-myBus-app#1]
Hi! 
I really like your work here and it also seems to be prepared to be easily extended by others. But I could not find a license the code is published under. 
Would you consider adding a OSS license like the MIT one to allow other to extend the code for their cities public transports?

Best Regards
Marion

**Comment by kolitiri** [comment]
Hi @marknp license ready. Enjoy!

Not sure what API you are going to extend it with, but bear in mind that large responses (by TFL API) cannot be handled by the watch (at least not Garmin fenix 3-5. Could be better now with model 6)

That was the reason why I was using an auxiliary service ([myBus-web-service-async](https://github.com/kolitiri/myBus-web-service-async)) in order to filter and skim the responses prior to forwarding them back to the watch.

There is an option in the config to make requests either directly to TFL or to an auxiliary service. You'll figure it out ;)

**Comment by marknp** [comment]
thanks for the quick action! 

I am using the API of the public transport in Munich Germany (mvg) on my Venu sq and have not had any issues yet with request sizes, but I am keeping the proxy service idea in mind if I run into issues.
In case you are interested: This is my fork I am working on, https://github.com/marknp/garmin-myBus-app. I also am trying to do some UI changes so I can better show the complete names of the stations - german names tend do be long :D

**Comment by kolitiri** [comment]
Oh that's nice then! I never really liked the proxy service idea..

If you need any help you can reach me on twitter.

Good luck with those German names :)
